import { NextResponse } from "next/server";



export async function GET() {
  const CoursesItems = [
    {
      id: 1,
      teacherName: "teacherName",
      teacherPosition: "teacherPosition",
      befourTitle: "befourTitle",
      title: "title",
      description: "description",
      largeDescription: "largeDescription",
      img: "/imgs/courseImg5.jpg",
      teacherImg: "/imgs/ShantMargaryan.png",
      link: "link",
    },
    {
      id: 2,
      teacherName: "secoundTeacherName",
      teacherPosition: "secoundTeacherPosition",
      befourTitle: "secoundBefourTitle",
      title: "secoundTitle",
      description: "secoundDescription",
      largeDescription: "secoundLargeDescription",
      img: "/imgs/courseImg4.jpg",
      teacherImg: "/imgs/VahanHovhannisian.png",
      link: "link",
    },
    {
      id: 3,
      teacherName: "thirdTeacherName",
      teacherPosition: "thirdTeacherPosition",
      befourTitle: "thirdBefourTitle",
      title: "thirdTitle",
      description: "thirdDescription",
      largeDescription: "thirdLargeDescription",
      img: "/imgs/courseImg2.jpg",
      teacherImg: "/imgs/KarenHarutyunyan.png",
      link: "link",
    },
    {
      id: 4,
      teacherName: "fourthTeacherName",
      teacherPosition: "fourthTeacherPosition",
      befourTitle: "fourthBefourTitle",
      title: "fourthTitle",
      description: "fourthDescription",
      largeDescription: "fourthLargeDescription",
      img: "/imgs/courseImg3.jpg",
      teacherImg: "/imgs/MarineTorosyan.png",
      link: "link",
    },
    {
      id: 5,
      teacherName: "fifthTeacherName",
      teacherPosition: "fifthTeacherPosition",
      befourTitle: "fifthBefourTitle",
      title: "fifthTitle",
      description: "fifthDescription",
      largeDescription: "fifthLargeDescription",
      img: "/imgs/courseImg1.jpg",
      teacherImg: "/imgs/VahanHovhannisian.png",
      link: "link",
    },
    {
      id: 6,
      teacherName: "sixthTeacherName",
      teacherPosition: "sixthTeacherPosition",
      befourTitle: "sixthBefourTitle",
      title: "sixthTitle",
      description: "sixthDescription",
      largeDescription: "sixthLargeDescription",
      img: "/imgs/courseImg6.jpg",
      teacherImg: "/imgs/HasmikArshakyan.png",
      link: "link",
    },
    {
      id: 7,
      teacherName: "seventhTeacherName",
      teacherPosition: "seventhTeacherPosition",
      befourTitle: "seventhBefourTitle",
      title: "seventhTitle",
      description: "seventhDescription",
      largeDescription: "seventhLargeDescription",
      img: "/imgs/courseImg7.webp",
      teacherImg: "/imgs/SyuziSargsyan.png",
      link: "link",
    },
  ];
  return NextResponse.json(CoursesItems);
}

